### PR TITLE
 Initial PR for Flare/Broadcast Web Application

### PR DESCRIPTION
**Pull request by abeasley1722**
This is the initial PR for Flare/Broadcast, setting up the frontend and backend containers for the web application. Please review all files within this directory, as everything here is new. I initially made the mistake of pushing changes before creating a main branch. To enable this PR, I’ve added minor changes (extra spaces) to mark files as different. Any requested changes will be added in this branch.

#### Areas to Review
1. **Shared Volume**:
   - Confirm that the shared volume is properly mounted within both the frontend and backend containers.
  
2. **Static Files and Test Chart Data**:
   - Verify that Nginx is serving static files correctly. You can confirm by visiting the localhost URL and checking:
     - The Vue page loads as expected.
     - A sample CSV file displays in plain text when the "Test" button is clicked.

3. **Nginx User Setup for Frontend Container**:
   - Ensure the frontend container runs under the `nginx` user instead of `root`. 
     - To confirm, run:
       ```bash
       docker exec -it flare-frontend id
       ```
     - If the output lists `nginx` as the user, the setup is correct.
  
**P.S. Since you can't properly review, please comment below this PR with the file and line number that you want changed.**

Please let me know if any additional information is needed. Thank you for reviewing this setup!

### CODE REVIEW

**Comment by snguyen1** [comment]
If we're going to create another `main` (`main-1` in this case) branch, please consider creating and using `develop` branch instead.

**Comment by snguyen1** [comment]
Please add .gitignore file at root directory.
- File such as `.env` are not supposed to be added to the code.  Also, in the README.md, instruct people to clone the `.env.dist` and modify it.
- File produced by python such as `*.pyc` are not supposed to be added to the repo, so add them to .gitignore file 
- Directories such as `venv` should be git-ignored.
- `**/node-modules` should be git-ignored as well

**Comment by snguyen1** [comment]
Typically, we don't need to use `src`, I personally think backend and frontend directory should be in the root directory.
For directory naming, consider sticking to all-lowercase.

**Comment by snguyen1** [comment]
feature branch name should follow `semaphore` repo branch name convention (if there are any) to avoid confusion when the team has new members

**Comment by snguyen1** [comment]
On README.md, `Vue Development Setup`,
- Missing the step to run `npm install`
- On step 1, be more specific on what command to use (`nvm install ....`, then `nvm use ...`, then `node -v`. Also, if it's good to have a hyperlink to download nvm.

**Comment by snguyen1** [comment]
On  `env.dist`, you can enter a default value to FRONTEND_HOST_PORT (example: 8100)

**Comment by snguyen1** [comment]
FYI, by default I think Vue uses 5173 on `npm run dev`.
You can change the port to a more common one by adding `port` key and value in `vite.config.js` on `server` section.

**Comment by snguyen1** [comment]
image
I run docker-compose and got this error

**Review by snguyen1 — COMMENTED** [review]
See comments in the Conversation tab

**Comment by abeasley1722** [comment]
Regarding this error,  it seems my local changes aren't being picked up as changes and added to the branch. The directory for ui-vue is using the wrong name, while the cspec directory is not being shown. I will fix this as soon as possible. When the ui-view is named correctly and the data/cspec directory is added it works as expected.
image

**Pull request closed without merging**
